# Utilisation de l'image PHP Apache
FROM php:apache
# Copier les fichiers de votre application dans le conteneur

COPY . /var/www/html/

# Installer les extensions PDO MySQL
RUN docker-php-ext-install pdo pdo_mysql

# Exposer le port 80 du conteneur
EXPOSE 80